### ISSUE TITLE
추가할 알고리즘

### ISSUE THREAD

**Issue by powergee** [ICPC-White-Whale/icpc-team-note#3]
## 참고: 2020년에 쓴 알고리즘

1. Tree
    * [x] LCA - 최문기
    * [x] Segment Tree - **김정현** (실행 시간 보기)
    * [x] Segment tree with lazy propagation - **김정현**
    * [x] Persistent Segment Tree -> 작년꺼 그대로
    * [x] Li-Chao Tree - **최문기**
    * [x] Merge Sort Tree - **김정현**
    * [x] Centroid -> 작년꺼 그대로
2. Graph
    * [x] Dinic's Algorithm - **최문기**
    * [x] Hopcroft-Karp - **최문기**
    * [x] Vertex cover - **최문기**
    * [x] MCMF - **최문기**
    * [x] SCC - **최문기**
    * [x] 2-SAT - **최문기**
    * [x] Bellman-Ford -> 작년꺼 그대로
    * [x] Dijkstra -> 작년꺼 그대로
    * [x] Floyd-Warshall -> 작년꺼 그대로
    * [x] BCC - **최문기**
3. String
    * [x] KMP - **김정현**
    * [x] Trie - **김정현**
    * [x] Aho-Corasick - **김정현**
    * [x] Suffix Array / LCP - **김정현**
4. Geometry
    * [x] Convex Hull - **최문기**
    * [x] Rotating Calipers - **최문기**
5. Math
    * [x] FFT - **오규민**
    * [x] Fermat's Little Theorem - 작년꺼 그대로
    * [x] Extended Euclidian Algorithm - 작년꺼 그대로
6. Dynamic Programming
    * [x] Knuth -> 김정현
    * [x] Divide and Conquer -> 김정현
    * [x] O(n) Convex Hull Trick - 오규민 **(double 쓰지 말 것, O(n)으로 구현, O(nlogn)은 리차오 쓰면 됨)**
7. Etc.
    * [x] Mo's Algorithm - 작년꺼 그대로
    * [x] 히스토그램에서 가장 큰 직사각형 - 작년꺼 그대로
    * [x] 가장 가까운 두 점 - 작년꺼 그대로
    * [x] iknoom's segtree - 최문기

## 추가할 것

* [x] 삼분탐색 - 최문기
* [x] 선분교차 - 최문기

**Comment by iknoom** [comment]
추적을 포함한 LIS
